sudo: required
services:
  - docker

before_install:
  - docker build -t psw0946/docker-react -f Dockerfile.dev .

script:
  - docker run psw0946/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker" # app name of the elasticbeanstalk
  env: "Docker-env" # environment name of the elasticbeanstalk
  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
  bucket_path: "docker" # same as app name
  on:
    branch: master # whenever pushing master branch, deploy start
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY