apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: stephengrider/multi-worker # assume that this image is on the docker-hub.
      ports:
        - containerPort: 9999